/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project01;

public class App {
  public static void main(String[] args) {

    System.out.println("지출 내역 관리 시스템");
    System.out.println("----------------------------------");

    System.out.print("번호: ");
    System.out.println(100);

    System.out.printf("지출명: %s", "아이스 아메리카노");
    System.out.println();

    System.out.printf("금액: %d 원" + 1400);

    System.out.printf("생필품: (Yes(Y), No(n)): %c\n", 'n');

  }
}
